### ISSUE TITLE
LateInitializationError: Field 'alphaAnimation' has not been initialized.

### ISSUE THREAD

**Issue by AlexanderShirokih** [apgapg/avatar_glow#17]
I got the next error after updating to version 2.0.0:

```
The following LateError was thrown building AvatarGlow(dirty, state: _AvatarGlowState#4a8d4):
LateInitializationError: Field 'alphaAnimation' has not been initialized.

The relevant error-causing widget was: 
  AvatarGlow 
When the exception was thrown, this was the stack: 
#0      _AvatarGlowState.alphaAnimation (package:avatar_glow/avatar_glow.dart)
#1      _AvatarGlowState.build (package:avatar_glow/avatar_glow.dart:140:18)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4704:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4587:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759:11)
```

The error occurs when I start with `animate: false`

**Comment by nurassylive** [comment]
I also have this issue...

**Comment by apgapg** [comment]
I tried running the example and it works fine.
Can you let me the output of `flutter doctor -v`?
I guess this something to null safety on older flutter sdks

**Comment by nurassylive** [comment]
<img width="823" alt="Screen Shot 2021-03-13 at 15 16 05" src="https://user-images.githubusercontent.com/15155392/111025573-309e7900-840f-11eb-8bf6-028b0c5bf644.png">
Here you go. I think everything is ok...

**Comment by apgapg** [comment]
@nurassylive Thanks for sharing this info. I do not what is going wrong over here.
Can you share a sample reproducing the same error?

**Comment by nurassylive** [comment]
My Source Code:
<img width="524" alt="Screen Shot 2021-03-13 at 15 56 23" src="https://user-images.githubusercontent.com/15155392/111028700-7284ea80-8422-11eb-8eba-64ed18b4284f.png">

Error on device:
![WhatsApp Image 2021-03-13 at 5 26 13 PM](https://user-images.githubusercontent.com/15155392/111028706-7dd81600-8422-11eb-8443-076cd3244c65.jpeg)

Issue on console:
<img width="1158" alt="Screen Shot 2021-03-13 at 17 35 49" src="https://user-images.githubusercontent.com/15155392/111028728-a3651f80-8422-11eb-8766-217b46b53249.png">

**Comment by apgapg** [comment]
Hi @nurassylive Thanks for sharing information.
I tried revamping the whole code and its likely the error is resolved.
Can you please check on the latest once?
```yaml
  avatar_glow:
    git:
      url: https://github.com/apgapg/avatar_glow
      ref: master
```
So that i can release the new version then.

Thanks in advance.

**Comment by AlexanderShirokih** [comment]
New version works fine for my case. Thanks.

**Comment by apgapg** [comment]
Nice i will now publish new version 2.0.1

**Comment by apgapg** [comment]
v2.0.1 released 🎉

**Comment by apgapg** [comment]
Please reopen the issue if error persists.
Thanks @nurassylive @AlexanderShirokih
