### ISSUE TITLE
Null Exception after Delay

### ISSUE THREAD

**Issue by scottdewald** [apgapg/avatar_glow#2]
Thanks for you work on this widget. I am enjoying using it.

I had multiple AvatarGlow widgets in a scrollable list and as the list was scrolled, Flutter automatically calls dispose() on those widgets which go off the screen. There is a small bug in which you need to check if the widget is still 'mounted' after the Future.delay() async call. Without this, it was throwing a null exception as it was trying to call 'controller.reset()' after 'controller.dispose()' had been called. Just add the following check inside initState():

    await Future.delayed(
      widget.repeatPauseDuration ?? Duration(milliseconds: 100));

    // TODO: begin fix
    if (mounted) {
      controller.reset();
      controller.forward();
    }
    // TODO: end fix

`mounted` is a built-in Widget property which tells you if the Widget has been disposed.

**Comment by xsahil03x** [comment]
Hey @scottdewald thanks for submitting the issue and its fix. We really appreciate it.
