### ISSUE TITLE
Question, Radius parameter taking too much screen space

### ISSUE THREAD

**Issue by Technorocker** [apgapg/avatar_glow#29]
So I was using this plugin for my profile avatar which was placed in the upper center of the screen, I'm readjusting my layout and now the profile avatar is close to the edge of screen. Unless I want a super small avatar picture I cant adjust the radius enough that the invisible area around pic gets pushed out away from the edge in order to be able to see the glow coming out from under the picture. 

Am I missing something or is this just how the plugin is supposed to work?

**Comment by apgapg** [comment]
The outer glow would take space till the radius it needs untill glow disappears.
You can set radius via parameter .

**Comment by bradintheusa** [comment]
Take a look at my fork, I did a fix to allow what you want.  It lets the glow overlap other widgets.

![image](https://github.com/apgapg/avatar_glow/assets/1160356/dc80a0db-2b65-418d-8cfc-958531c46e1c)
