### ISSUE TITLE
[QUESTION] Project outdated

### ISSUE THREAD

**Issue by vtisnado** [apgapg/avatar_glow#30]
Hey everyone,

Just wanted to give you a heads up that it's been over 18 months since the project was last updated, and the latest stable version came out in Oct 2021. I'm interested to know if there are any future plans for the project or if there's any way I can contribute to its development.

Thanks for your dedication to this project!

**Comment by apgapg** [comment]
Yes, due to limited bandwidth I am not able to update the project.
Your help will be appreciated

**Comment by bradintheusa** [comment]
I can assist if needed

**Comment by apgapg** [comment]
@bradintheusa thanks. Let me know how we can collaborate

**Comment by bradintheusa** [comment]
I can do a PR to update the example and then look at some of those open issues.

**Comment by apgapg** [comment]
@bradintheusa okay sure
