### ISSUE TITLE
Using on floatingActionButton

### ISSUE THREAD

**Issue by pishguy** [apgapg/avatar_glow#4]
how can i avoid resize floatingActionButton when thats child of `avatar_grow`? thats cause of make the larger margin 

[ScreenShot](http://s6.uplod.ir/i/00953/kgsd3xzvgzcf.png)

```
Scaffold(
  key: _scaffoldKey,
  primary: true,
  resizeToAvoidBottomPadding: false,
  appBar: ApplicationToolbar(title: title),
  floatingActionButton: AvatarGlow(
    startDelay: Duration(milliseconds: 1000),
    glowColor: Colors.blue,
    endRadius: 90.0,
    duration: Duration(milliseconds: 2000),
    repeat: true,
    showTwoGlows: true,
    repeatPauseDuration: Duration(milliseconds: 100),
    child: Builder(
        builder: (context) => FloatingActionButton(
              child: Icon(Icons.add),
              onPressed: () {
                _settingModalBottomSheet(context);
              },
            )),
  ),
  floatingActionButtonLocation:
      FloatingActionButtonLocation.centerDocked,
  bottomNavigationBar: AppBottomNavigationBar(),
  drawer: AppDrawer(),
  body: _fragments[_currentIndex],
),
```
how can we using feature like with `z-index` to avoid resize?

**Comment by apgapg** [comment]
Hi @MahdiPishguy sorry for late response. Indeed thats a good issue. Actually the glow's container is taking extra space thats why the notch appears too large. Right now i cant think of a solution for this. Do you have any approach to achieve this?

**Comment by apgapg** [comment]
@xsahil03x Any solution for this?

**Comment by MahdiPishguy** [comment]
@xsahil03x hi, i can't find any solution and i have this problem yet

**Comment by apgapg** [comment]
I guess you have to make use of overlays here which is a little tricky. We
cant use this package directly here. We'll have to copy its code and use it
in overlays

**Comment by apgapg** [comment]
@gildurao Any solution for this issue? I can't find a way out

**Comment by bradintheusa** [comment]
I made a fork that should solve this issue. I'll clean it up and add a PR

**Comment by minhx3** [comment]
> I made a fork that should solve this issue. I'll clean it up and add a PR

can you share your solution? thank.

**Comment by bradintheusa** [comment]
Here:  https://github.com/bradintheusa/avatar_glow_plus

I plan to merge it back in. The change is basically just this one line

`return UnconstrainedBox(`

but it has some debug noise which is unfortunate.

**Comment by xsahil03x** [comment]
@bradintheusa can you also share a small screenshot or video of this looks?

**Comment by bradintheusa** [comment]
There's an example in that repo. It's not specifically a `floatingActionButton` but I think the concept means it will work
