### ISSUE TITLE
More than two glows

### ISSUE THREAD

**Issue by tasqyn** [apgapg/avatar_glow#7]
Hi, very cool package thanks for this.  I need more than two glows. I see there is only `showTwoGlows`. Is it supported/possible to increase glow numbers?

**Comment by MahdiPishguy** [comment]
+1

i need to have this feature

**Comment by apgapg** [comment]
Yes it can be done. We can have a parameter which takes glows count. 
I can't provide it right now. Little busy with other stuffs. You can edit the library and can do easily.
Also if PR can be raised its highly welcome
