### ISSUE TITLE
error: The argument type 'Animation<dynamic>' can't be assigned to the parameter type 'Animation<double>'

### ISSUE THREAD

**Issue by MahdiPishguy** [apgapg/avatar_glow#8]
how can i resolve this analysis problem on this line of code:

```
final Animation curve = CurvedAnimation(parent: controller, curve: Curves.decelerate);
smallDiscAnimation = Tween(begin: (widget.endRadius * 2) / 6, end: (widget.endRadius * 2) * (3 / 4)).animate(curve)
```
analysis problem is for this part of code : `.animate(curve)`

**Comment by apgapg** [comment]
Might be due to flutter upgrade. Will need to look in it

**Comment by apgapg** [comment]
I didn't reproduce it. 
Please reopen if you face this again

**Comment by manoharkharvi43** [comment]
The argument type 'Animation<double>?' can't be assigned to the parameter type 'Animation<double>'.
Same issue is coming.

**Comment by itsdani121** [comment]
i think you set this as like 

            final Animation<double> curve = CurvedAnimation(parent: controller, curve: Curves.decelerate);
                    smallDiscAnimation = Tween(begin: (widget.endRadius * 2) / 6, end: (widget.endRadius * 2) * (3 / 4)).animate(curve)

**Comment by ahtsaa29** [comment]
You can use 
    _controller = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 300));

    _curve = CurvedAnimation(parent: _controller, curve: Curves.slowMiddle);

    _colorAnimation =
        _curve.drive(ColorTween(begin: Colors.grey[400], end: Colors.red));
        
        
        this will help you

**Comment by Priyanshu078** [comment]
@ahtsaa29 Thank you for the answer
